//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QAssetBundle
{
    
    public class A_png
    {
        public const string BundleName = "a_png";
        public const string A = "a";
    }
    public class Assetobj_1_prefab
    {
        public const string BundleName = "assetobj 1_prefab";
        public const string ASSETOBJ_1 = "assetobj 1";
    }
    public class Assetobj_2_prefab
    {
        public const string BundleName = "assetobj 2_prefab";
        public const string ASSETOBJ_2 = "assetobj 2";
    }
    public class Assetobj_3_prefab
    {
        public const string BundleName = "assetobj 3_prefab";
        public const string ASSETOBJ_3 = "assetobj 3";
    }
    public class Assetobj_prefab
    {
        public const string BundleName = "assetobj_prefab";
        public const string ASSETOBJ = "assetobj";
    }
    public class B_png
    {
        public const string BundleName = "b_png";
        public const string B = "b";
    }
    public class Beizhi_jiaobanbang_prefab
    {
        public const string BundleName = "beizhi_jiaobanbang_prefab";
        public const string BEIZHI_JIAOBANBANG = "beizhi_jiaobanbang";
    }
    public class Beizhi_shigaofen_prefab
    {
        public const string BundleName = "beizhi_shigaofen_prefab";
        public const string SHIGAOFEN = "shigaofen";
    }
    public class Beizhishigao_prefab
    {
        public const string BundleName = "beizhishigao_prefab";
        public const string BEIZHISHIGAO = "beizhishigao";
    }
    public class Button_ps_prefab
    {
        public const string BundleName = "button_ps_prefab";
        public const string BUTTON_PS = "button_ps";
    }
    public class C_png
    {
        public const string BundleName = "c_png";
        public const string C = "c";
    }
    public class Chengxing_hu_prefab
    {
        public const string BundleName = "chengxing_hu_prefab";
        public const string CHENGXING_HU = "chengxing_hu";
    }
    public class Experimentalreportpanel_prefab
    {
        public const string BundleName = "experimentalreportpanel_prefab";
        public const string EXPERIMENTALREPORTPANEL = "experimentalreportpanel";
    }
    public class Exprimainpanel_prefab
    {
        public const string BundleName = "exprimainpanel_prefab";
        public const string EXPRIMAINPANEL = "exprimainpanel";
    }
    public class Guadao_prefab
    {
        public const string BundleName = "guadao_prefab";
        public const string GUADAO = "guadao";
    }
    public class Gudingjingshu_prefab
    {
        public const string BundleName = "gudingjingshu_prefab";
        public const string GUDINGJINGSHU = "gudingjingshu";
    }
    public class Helppagepanel_prefab
    {
        public const string BundleName = "helppagepanel_prefab";
        public const string HELPPAGEPANEL = "helppagepanel";
    }
    public class Imageprefaba_prefab
    {
        public const string BundleName = "imageprefaba_prefab";
        public const string IMAGEPREFABA = "imageprefaba";
    }
    public class Imageprefabb_prefab
    {
        public const string BundleName = "imageprefabb_prefab";
        public const string IMAGEPREFABB = "imageprefabb";
    }
    public class Imageprefabc_prefab
    {
        public const string BundleName = "imageprefabc_prefab";
        public const string IMAGEPREFABC = "imageprefabc";
    }
    public class Jinshudao_prefab
    {
        public const string BundleName = "jinshudao_prefab";
        public const string JINSHUDAO = "jinshudao";
    }
    public class Knowassessmentpanel_prefab
    {
        public const string BundleName = "knowassessmentpanel_prefab";
        public const string KNOWASSESSMENTPANEL = "knowassessmentpanel";
    }
    public class Knowchangepanel_prefab
    {
        public const string BundleName = "knowchangepanel_prefab";
        public const string KNOWCHANGEPANEL = "knowchangepanel";
    }
    public class Knowledgelearpanel_prefab
    {
        public const string BundleName = "knowledgelearpanel_prefab";
        public const string KNOWLEDGELEARPANEL = "knowledgelearpanel";
    }
    public class Mainmenupanel_prefab
    {
        public const string BundleName = "mainmenupanel_prefab";
        public const string MAINMENUPANEL = "mainmenupanel";
    }
    public class Mozhong_prefab
    {
        public const string BundleName = "mozhong_prefab";
        public const string MOZHONG = "mozhong";
    }
    public class Muchui_prefab
    {
        public const string BundleName = "muchui_prefab";
        public const string MUCHUI = "muchui";
    }
    public class Mudao_prefab
    {
        public const string BundleName = "mudao_prefab";
        public const string MUDAO = "mudao";
    }
    public class Mudaoone_prefab
    {
        public const string BundleName = "mudaoone_prefab";
        public const string MUDAOONE = "mudaoone";
    }
    public class Niba_prefab
    {
        public const string BundleName = "niba_prefab";
        public const string NIBA = "niba";
    }
    public class Nibaduo_prefab
    {
        public const string BundleName = "nibaduo_prefab";
        public const string NIBADUO = "nibaduo";
    }
    public class Nijiang_01_prefab
    {
        public const string BundleName = "nijiang_01_prefab";
        public const string NIJIANG_01 = "nijiang_01";
    }
    public class Nijiang_02_prefab
    {
        public const string BundleName = "nijiang_02_prefab";
        public const string NIJIANG_02 = "nijiang_02";
    }
    public class Operationexperipanel_prefab
    {
        public const string BundleName = "operationexperipanel_prefab";
        public const string OPERATIONEXPERIPANEL = "operationexperipanel";
    }
    public class Pen_prefab
    {
        public const string BundleName = "pen_prefab";
        public const string PEN = "pen";
    }
    public class Ruanbang_prefab
    {
        public const string BundleName = "ruanbang_prefab";
        public const string RUANBANG = "ruanbang";
    }
    public class Sceneres_unity
    {
        public const string BundleName = "sceneres_unity";
        public const string SCENERES = "sceneres";
    }
    public class Spriteatlas_spriteatlas
    {
        public const string BundleName = "spriteatlas_spriteatlas";
        public const string SPRITEATLAS = "spriteatlas";
    }
    public class Starttestpanel_prefab
    {
        public const string BundleName = "starttestpanel_prefab";
        public const string STARTTESTPANEL = "starttestpanel";
    }
    public class Step_yimo_zhujiang_kouzi_prefab
    {
        public const string BundleName = "step_yimo_zhujiang_kouzi_prefab";
        public const string STEP_YIMO_ZHUJIANG_KOUZI = "step_yimo_zhujiang_kouzi";
    }
    public class Tanlidai_prefab
    {
        public const string BundleName = "tanlidai_prefab";
        public const string TANLIDAI = "tanlidai";
    }
    public class Textureexample1_png
    {
        public const string BundleName = "textureexample1_png";
        public const string TEXTUREEXAMPLE1 = "textureexample1";
    }
    public class Tianni_niba_kuai_xiuzheng_prefab
    {
        public const string BundleName = "tianni_niba_kuai_xiuzheng_prefab";
        public const string TIANNI_NIBA_KUAI_XIUZHENG = "tianni_niba_kuai_xiuzheng";
    }
    public class Tittlepanel_prefab
    {
        public const string BundleName = "tittlepanel_prefab";
        public const string TITTLEPANEL = "tittlepanel";
    }
    public class Tuomoji_prefab
    {
        public const string BundleName = "tuomoji_prefab";
        public const string TUOMOJI = "tuomoji";
    }
    public class Tuzi_prefab
    {
        public const string BundleName = "tuzi_prefab";
        public const string TUZI = "tuzi";
    }
    public class Uibasicpanel_prefab
    {
        public const string BundleName = "uibasicpanel_prefab";
        public const string UIBASICPANEL = "uibasicpanel";
    }
    public class Uimultipanel_prefab
    {
        public const string BundleName = "uimultipanel_prefab";
        public const string UIMULTIPANEL = "uimultipanel";
    }
    public class Uipanelwithimageprefab_prefab
    {
        public const string BundleName = "uipanelwithimageprefab_prefab";
        public const string UIPANELWITHIMAGEPREFAB = "uipanelwithimageprefab";
    }
    public class Uistackpanel1_prefab
    {
        public const string BundleName = "uistackpanel1_prefab";
        public const string UISTACKPANEL1 = "uistackpanel1";
    }
    public class Uistackpanel2_prefab
    {
        public const string BundleName = "uistackpanel2_prefab";
        public const string UISTACKPANEL2 = "uistackpanel2";
    }
    public class Water_prefab
    {
        public const string BundleName = "water_prefab";
        public const string WATER = "water";
    }
    public class Weiban_jiazi001_prefab
    {
        public const string BundleName = "weiban_jiazi001_prefab";
        public const string WEIBAN_JIAZI001 = "weiban_jiazi001";
    }
    public class Weiban_jiazi003_prefab
    {
        public const string BundleName = "weiban_jiazi003_prefab";
        public const string WEIBAN_JIAZI003 = "weiban_jiazi003";
    }
    public class Weiban_shengzi_001_prefab
    {
        public const string BundleName = "weiban_shengzi_001_prefab";
        public const string SHENGZI = "shengzi";
    }
    public class Weiban_weiban_prefab
    {
        public const string BundleName = "weiban_weiban_prefab";
        public const string WEIBAN_WEIBAN = "weiban_weiban";
    }
    public class Yakelibang_prefab
    {
        public const string BundleName = "yakelibang_prefab";
        public const string YAKELIBANG = "yakelibang";
    }
    public class Zhujiang_kouzi_prefab
    {
        public const string BundleName = "zhujiang_kouzi_prefab";
        public const string ZHUJIANG_KOUZI = "zhujiang_kouzi";
    }
    public class Zhujiangchengxing_nijiang_1_prefab
    {
        public const string BundleName = "zhujiangchengxing_nijiang 1_prefab";
        public const string ZHUJIANGCHENGXING_NIJIANG_1 = "zhujiangchengxing_nijiang 1";
    }
    public class Zhujiangchengxing_nijiang_prefab
    {
        public const string BundleName = "zhujiangchengxing_nijiang_prefab";
        public const string ZHUJIANGCHENGXING_NIJIANG = "zhujiangchengxing_nijiang";
    }
    public class Zhujiangchengxing_peiti_prefab
    {
        public const string BundleName = "zhujiangchengxing_peiti_prefab";
        public const string ZHUJIANGCHENGXING_PEITI = "zhujiangchengxing_peiti";
    }
    public class Zhujiangkou_jinshudao_prefab
    {
        public const string BundleName = "zhujiangkou_jinshudao_prefab";
        public const string ZHUJIANGKOU_JINSHUDAO = "zhujiangkou_jinshudao";
    }
    public class Zhujiangkou_neimo_prefab
    {
        public const string BundleName = "zhujiangkou_neimo_prefab";
        public const string ZHUJIANGKOU_NEIMO = "zhujiangkou_neimo";
    }
}
